---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: debian-7.7
  - name: debian-6.0.10

suites:
  - name: default
    run_list:
      - recipe[consul::default]
      - recipe[consul-alerts::default]
    attributes:
