name             'consul-alerts'
maintainer       'Adam Krone'
maintainer_email 'krone.adam@gmail.com'
license          'Apache v2.0'
description      'Installs/Configures consul-alerts'
long_description 'Installs/Configures consul-alerts'
version          '0.1.0'
